/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : AppointmentId,
  'status' : string,
  'clinicLocation' : string,
  'email' : string,
  'preferredDate' : Time,
  'preferredTime' : string,
  'patientName' : string,
  'phone' : string,
  'reason' : string,
}
export type AppointmentId = bigint;
export interface ContactMessage {
  'dateSubmitted' : Time,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Review {
  'id' : ReviewId,
  'dateSubmitted' : Time,
  'comment' : string,
  'patientName' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export type Time = bigint;
export interface _SERVICE {
  'addReview' : ActorMethod<[string, bigint, string], ReviewId>,
  'bookAppointment' : ActorMethod<
    [string, string, string, string, Time, string, string],
    AppointmentId
  >,
  'deleteReview' : ActorMethod<[ReviewId], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAppointment' : ActorMethod<[AppointmentId], Appointment>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];