/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReviewId = IDL.Nat;
export const Time = IDL.Int;
export const AppointmentId = IDL.Nat;
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'status' : IDL.Text,
  'clinicLocation' : IDL.Text,
  'email' : IDL.Text,
  'preferredDate' : Time,
  'preferredTime' : IDL.Text,
  'patientName' : IDL.Text,
  'phone' : IDL.Text,
  'reason' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'dateSubmitted' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'dateSubmitted' : Time,
  'comment' : IDL.Text,
  'patientName' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [ReviewId], []),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
      [AppointmentId],
      [],
    ),
  'deleteReview' : IDL.Func([ReviewId], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAppointment' : IDL.Func([AppointmentId], [Appointment], ['query']),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReviewId = IDL.Nat;
  const Time = IDL.Int;
  const AppointmentId = IDL.Nat;
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'status' : IDL.Text,
    'clinicLocation' : IDL.Text,
    'email' : IDL.Text,
    'preferredDate' : Time,
    'preferredTime' : IDL.Text,
    'patientName' : IDL.Text,
    'phone' : IDL.Text,
    'reason' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'dateSubmitted' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'dateSubmitted' : Time,
    'comment' : IDL.Text,
    'patientName' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [ReviewId], []),
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [AppointmentId],
        [],
      ),
    'deleteReview' : IDL.Func([ReviewId], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAppointment' : IDL.Func([AppointmentId], [Appointment], ['query']),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };